# Generated by Django 5.0.3 on 2024-03-31 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_register_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='date',
        ),
    ]
