# Generated by Django 5.0.3 on 2024-03-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_register_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
