# Generated by Django 5.0.3 on 2024-03-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_contact_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
